name: Event Dispatch Receiver

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print Payload
        run: echo 'Received payload => ${{github.event.client_payload.amba_branch}}'
